---
name: InfluxDB2
version: 0.0.2
slug: influxdb2
description: Scalable datastore for metrics, events, and real-time analytics. Running InfluxDB v2.x.
url: https://github.com/Dattel/homeassistant-influxdb2
startup: services
homeassistant: 0.92.0b2
webui: http://[HOST]:[PORT:8086]
hassio_api: true
arch:
  - aarch64
  - amd64
init: false
map:
  - share:rw
  - ssl
ports:
  8086/tcp: 8086
ports_description:
  8086/tcp: InfluxDB server
options:
  reporting: true
  ssl: false
  certfile: fullchain.pem
  keyfile: privkey.pem
  envvars: []
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  reporting: bool
  ssl: bool
  certfile: str
  keyfile: str
  envvars:
    - name: match(^INFLUXD_([A-Z0-9_])+$)
      value: str
